# Master config file for ODIS nodes, that drives the Dagster pipeline
# to update the ODIS graph.  Other important notes about this config file:
#  - sorted alphabetically by 'name' parameter
#  - no need to use quotes. Use the single-quoted style (') if characters 
#    such as " and \ are being used inside the string to avoid escaping them
#  - pid: should point to the ODISCat 'view' if available, such as https://catalogue.odis.org/view/689
#         or if not, use format: https://oceaninfohub.org/.well-known/org/[name]
#  - url: point to sitemap or sitegraph
#  - endpoint: point to API endpoint if available
#  - endpointNtype: CSW, CKAN, ERDDAP, WMS, REST API, etc.
#      note: listing node endpoints are helpful for others (and Dashboard) 
#            to discover the services available, even when the ODIS graph isn't 
#            using the endpoints directly
#  - dateadded: YYYY-MM-DD (the date that JSON-LD became available, but not
#               necessarily when it was included in the ODIS graph)
#  - headless: true if JSON-LD is embedded in page
#  - if a parameter has no value, leave blank (with no quotes)
---
sources:
- name: benguelacc
  propername: Benguela Current Convention (BCC) GeoData Portal
  catalogue: https://geodata.benguelacc.org/
  domain: https://www.benguelacc.org/  
  logo: https://static.tildacdn.com/tild3263-3132-4937-a166-373963646533/Skjermbilde_2020-12-.png
  #missing ODISCat entry
  pid: https://oceaninfohub.org/.well-known/org/benguelacc
  sourcetype: sitegraph
  url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-benguelacc/benguelacc-simple-graph.json
  endpoint1: https://geodata.benguelacc.org/catalogue/csw
  endpoint1type: CSW
  headless: false
  dateadded: 2022-04-13
  active: true
- name: caribbeanmarineatlas
  propername: "Caribbean Marine Atlas catalogue"
  catalogue: https://www.caribbeanmarineatlas.net/home/
  domain: https://www.caribbeanmarineatlas.net/  
  logo: "https://www.caribbeanmarineatlas.net/static/cma2/landing_page/images/logotipo_CMA_2019.svg"
  pid: https://catalogue.odis.org/view/616
  sourcetype: sitegraph  
  url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-caribbeanmarineatlas/caribbeanmarineatlas-simple-graph.json
  endpoint1: https://www.caribbeanmarineatlas.net/catalogue/csw
  endpoint1type: CSW  
  headless: false
  dateadded: 2022-04-13
  active: true  
- name: cioosatlantic
  propername: CIOOS Atlantic
  catalogue: https://catalogue.cioosatlantic.ca/
  domain: https://cioosatlantic.ca
  logo: https://cioosatlantic.ca/wp-content/themes/cioos-siooc-wordpress-theme/img/atlantic/cioos-atlantic_EN.svg?x79655
  #missing ODISCat entry
  pid: https://oceaninfohub.org/.well-known/org/cioosatlantic
  sourcetype: sitemap
  url: https://catalogue.cioosatlantic.ca/sitemap/sitemap.xml
  #url: https://catalogue.cioosatlantic.ca/sitemap/sitemap-1.xml
  endpoint1: https://cioosatlantic.ca/erddap/index.html
  endpoint1type: ERDDAP
  headless: true
  dateadded: 2022-06-04
  active: true
- name: inanodc
  propername: Indonesia National Oceanic Data Center
  catalogue: https://geonode.nodc.id
  domain: https://nodc.id  
  logo: https://nodc.id/dist/img/brin.png
  #missing ODISCat entry
  pid: https://oceaninfohub.org/.well-known/org/inanodc
  sourcetype: sitegraph  
  url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-ina-nodc/ina-nodc-simple-graph.json
  endpoint1: https://geonode.nodc.id/catalogue/csw
  endpoint1type: CSW 
  headless: false
  dateadded: 2022-04-05 
  active: true
- name: maspawio
  propername: MASPAWIO: Marine Spatial Atlas for the Western Indian Ocean
  catalogue: http://maspawio.net/
  domain: https://cordioea.net/
  logo: https://cordioea.net/wp-content/uploads/2017/09/Geonde.png
  pid: https://catalogue.odis.org/view/351
  sourcetype: sitegraph  
  url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-maspawio/maspawio-simple-graph.json
  endpoint1: http://maspawio.net/catalogue/csw
  endpoint1type: CSW
  headless: false
  dateadded: 2022-03-30 
  active: true
- name: pdh
  propername: Pacific Data Hub
  catalogue: https://pacificdata.org/data/dataset
  domain: https://pacificdata.org
  logo: https://pacificdata.org/themes/custom/spc/logo.png
  pid: https://catalogue.odis.org/view/689
  sourcetype: sitemap  
  #url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-pacificdatahub/sitemap.xml
  endpoint1: https://pacificdata.org/data/api/action/package_list
  endpoint1type: CKAN
  headless: true
  dateadded: 2022-07-25   
  active: false
- name: vliz
  propername: Flanders Marine Institute catalogue
  catalogue: https://pacificdata.org/data/dataset
  domain: https://pacificdata.org  
  logo: ""
  url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-vliz/vliz-simple-graph.json
  headless: false
  pid: http://example.org/vliz/orgs
  sourcetype: sitegraph
  domain: https://emodnet.ec.europa.eu/geonetwork/srv/eng/csw
  active: true  
- sourcetype: sitegraph
  name: emodnet
  logo: "https://emodnet.ec.europa.eu/sites/emodnet.ec.europa.eu/themes/emodnet/component-library/ec/static/media/logo--en.5055ef4f.svg"
  url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-emodnet/emodnet-simple-graph.json
  headless: false
  #pid: http://hdl.handle.net/1834/41372
  propername: "European Marine Observation and Data Network catalogue"
  domain: https://emodnet.ec.europa.eu/
  active: true
- sourcetype: sitemap
  name: pogo
  logo: ""
  url: https://oceanscape.org/organisation-sitemap.xml
  headless: true
  pid: http://example.org/pogo/experts
  propername: Pogo Keywords
  domain: https://oceanscape.org
  active: true
- sourcetype: sitegraph
  name: obps
  url: https://oih.oceanbestpractices.org/obps.json
  headless: false
  pid: http://example.org/invemar/obps
  propername: Ocean Best Practices
  domain: https://oih.oceanbestpractices.org
  active: true
- sourcetype: sitemap
  name: edmerp
  url: https://edmerp.seadatanet.org/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/seadatanet/edmerp
  propername: EDMERP SeaDataNet
  domain: https://edmerp.seadatanet.org
  active: true
- sourcetype: sitemap
  name: edmo
  url: https://edmo.seadatanet.org/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/seadatanet/edmo
  propername: EDMO SeaDataNet
  domain: https://edmo.seadatanet.org
  active: true
- sourcetype: sitegraph
  name: invemarexpert
  url: http://portete.invemar.org.co/chm/api/oih/expert?format=json
  headless: false
  pid: http://example.org/invemar/experts
  propername: INVEMAR Experts
  domain: http://portete.invemar.org.co/chm/api/oih/expert
  active: true
- sourcetype: sitegraph
  name: invemardocuments
  url: http://portete.invemar.org.co/chm/api/oih/documents?format=json
  headless: false
  pid: http://example.org/invemar/documents
  propername: INVEMAR documents
  domain: http://portete.invemar.org.co/chm/api/oih/documents
  active: true
- sourcetype: sitegraph
  name: invemarinstitution
  url: http://portete.invemar.org.co/chm/api/oih/institution?format=json
  headless: false
  pid: http://example.org/invemar/institution
  propername: INVEMAR institution
  domain: http://portete.invemar.org.co/chm/api/oih/institution
  active: true
- sourcetype: sitegraph
  name: invemarvessel
  url: http://portete.invemar.org.co/chm/api/oih/vessel?format=json
  headless: false
  pid: http://example.org/invemar/vessel
  propername: INVEMAR vessel
  domain: http://portete.invemar.org.co/chm/api/oih/vessel
  active: true
- sourcetype: sitegraph
  name: invemartraining
  url: http://portete.invemar.org.co/chm/api/oih/training?format=json
  headless: false
  pid: http://example.org/invemar/training
  propername: INVEMAR training
  domain: http://portete.invemar.org.co/chm/api/oih/training
  active: true
- sourcetype: sitegraph
  name: aquadocs
  url: https://oih.aquadocs.org/aquadocs.json
  headless: false
  pid: http://hdl.handle.net/1834/41372
  propername: AquaDocs
  domain: https://aquadocs.org
  active: true
- sourcetype: sitemap
  name: marinetraining
  url: https://www.marinetraining.eu/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/marinetraining
  propername: Marine Training EU
  domain: https://marinetraining.eu/
  active: true
- sourcetype: sitemap
  name: euroceanprojects
  url: https://infohub.eurocean.net/sitemap/projects
  headless: false
  pid: http://example.org/eurocean/projects
  propername: EurOcean Projects
  domain: https://infohub.eurocean.net/data/projects
  active: true
- sourcetype: sitemap
  name: euroceanvessels
  url: https://infohub.eurocean.net/sitemap/vessels
  headless: false
  pid: http://example.org/invemar/documents
  propername: EurOcean vessels
  domain: https://infohub.eurocean.net/data/vessels
  active: true
- sourcetype: sitemap
  name: euroceanorgs
  url: https://infohub.eurocean.net/sitemap/organizations
  headless: false
  pid: http://example.org/invemar/documents
  propername: EurOcean Organizations
  domain: https://infohub.eurocean.net/data/organizations
  active: true
- sourcetype: sitemap
  name: obis
  url: https://obis.org/sitemap/sitemap_datasets.xml
  headless: false
  pid: https://www.re3data.org/repository/obis
  propername: Ocean Biodiversity Information System
  domain: https://obis.org
  active: true
- sourcetype: sitemap
  name: oceanexperts
  url: https://oceanexpert.org/assets/sitemaps/sitemapIndex.xml
  headless: false
  pid: https://www.re3data.org/repository/oceanexpert
  propername: OceanExpert UNESCO/IOC Project Office for IODE
  domain: https://oceanexpert.org/
  active: true
- sourcetype: sitemap
  name: euroceanexpert
  logo: ""
  url: https://www.oceanexpert.org/assets/sitemaps/sitemapExperts.xml
  headless: false
  pid: http://example.org/eurocean/experts
  propername: EurOcean Experts
  domain: https://infohub.eurocean.net/data/experts
  active: true
- sourcetype: sitemap
  name: euroceanevents
  logo: ""
  url: https://www.oceanexpert.org/assets/sitemaps/sitemapEvents.xml
  headless: false
  pid: http://example.org/eurocean/events
  propername: EurOcean Events
  domain: https://infohub.eurocean.net/data/events
  active: true
- sourcetype: sitemap
  name: euroceantraining
  logo: ""
  url: https://www.oceanexpert.org/assets/sitemaps/sitemapTraining.xml
  headless: false
  pid: http://example.org/eurocean/training
  propername: EurOcean training
  domain: https://infohub.eurocean.net/data/training
  active: true
- sourcetype: sitemap
  name: euroceanorgs
  logo: ""
  url: https://www.oceanexpert.org/assets/sitemaps/sitemapInstitutions.xml
  headless: false
  pid: http://example.org/eurocean/orgs
  propername: EurOcean Organizations
  domain: https://infohub.eurocean.net/data/organizations
  active: true

#- sourcetype: sitemap
  #name: marineie
  #url: http://data.marine.ie/geonetwork/srv/eng/portal.sitemap
  #headless: true
  #pid: https://www.re3data.org/repository/marineie
  #propername: Marine Institute Data Catalogue
  #domain: http://data.marine.ie
  #active: true
